myloglink: "/TXT/mylog.txt"
githublink: "https://github.com/jasonirvine76/os222"
author: "Jason Irvine Mahendra Putra"
title: "OS222: Operating Systems 2022-2"
tarballlink: "https://os.vlsm.org/Log/jasonirvine76.tar.bz2.txt"
copyright: "2022"
version: "1.0"
